[package]
name = "yamis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
cfg-if = "0.1"
colored = "2"
toml = "0.5"
lazy_static = "1.4"
serde_derive = "1.0"
serde = {version = "1.0", features = ["derive"]}
uuid = { version = "0.8.1", features = ["serde", "v4"] }
ctrlc = "3.2"

[[bin]]
name = "yamis"
path = "src/main.rs"