[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update & apt-get install -y pkg-config libssl-dev"]

[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update & apt-get install -y pkg-config libssl-dev"]
