[tasks.build-releases]
wd = ""
script = """
cross build --target x86_64-apple-darwin --release --target-dir=target_releases/v{1}
cross build --target x86_64-pc-windows-gnu --release --target-dir=target_releases/v{1}
cross build --target x86_64-unknown-linux-gnu --release --target-dir=target_releases/v{1}
"""

[tasks.package-releases]
wd = ""
program = "python"
args = ["zip_releases.py", "{1}"]

[tasks.cleanup]
wd = ""
script = "rm -r target_releases/v{1}"

[tasks.cleanup.windows]
wd = ""
script = "rmdir {(target_releases/v)1} /s /q"

[tasks.pack]
serial = ["build-releases", "package-releases", "cleanup"]

[tasks.test]
wd = ""
script = """
cross test --target x86_64-apple-darwin
cross test --target x86_64-pc-windows-gnu
cross test --target x86_64-unknown-linux-gnu
"""