[tasks.hello_world]
script = "echo Hello World"

[tasks.hello_world_script]
script = "echo Hello World"

[tasks.multiline_script]
script = """
echo Hello World
echo Hello World again
echo hello hello
"""

[tasks.inline_python]
script = "python -c \"{*}\""

[tasks.python]  # Example of an interactive application
script = "python"

[tasks.working_dir]
wd = "../yamis"
script = "dir"

[tasks.env_sample]
script = "echo %SAMPLE_VAR% %PATH% %NON_EXISTING%"

[tasks.env_sample.env]
SAMPLE_VAR = "SAMPLE"

[tasks.os_sample]
script = "echo hello linux"

[tasks.os_sample.windows]
script = "echo hello windows"

[tasks.os_sample.macos]
script = "echo hello macos"