[tasks.hello_world]
script = "echo Hello World"

[tasks.hello_world_script]
script = "echo Hello World"

[tasks.multiline_script]
script = """
echo Hello World
echo Hello World again
echo hello hello
"""

[tasks.inline_python]
script = "python -c {*}"

[tasks.python]  # Example of an interactive application
script = "python"