[tasks.hello_world]
command = "echo"
params = ["Hello World"]

[tasks.hello_world_script]
script = "echo Hello World"

[tasks.inline_python]
program = "python"
params = ["-c", "{*}"]

[tasks.python]  # Example of an interactive application
program = "python"