# TODO: Replace by something that can be tested
[tasks.command]
command = "echo"
params = ["Hello World"]

[tasks.script]
script = "echo Hello World"

[tasks.program]
program = "python"
params = ["-c", "print(\"{-m}\")"]

[tasks.python]  # Example of an interactive application
program = "python"